### ISSUE TITLE
Chromedriver is running after test are done.

### ISSUE THREAD

**Issue by FFFFFF** [webdriverio/cucumber-boilerplate#204] opened 2018-04-03 10:27 UTC
# Issue description
Chromedriver is running after test are done.

# Steps to reproduce
- git clone
- npm install
- changed `phantomjs` to `chrome` in `wdio.BUILD.conf.js`
- node_modules\\.bin\\wdio wdio.BUILD.conf.js

# Expected behavior
I expect chromedriver process is closed.

# Actual behavior
I see [chromedriver is running](http://prntscr.com/j065yw). 

# Issue occurred on browser/platform 
Windows 10 Pro 64x
Сhrome Version 65.0.3325.181 (Official Build) (64-bit)
"wdio-cucumber-framework": "~1.1.0",
"wdio-phantomjs-service": "~0.2.2",
"wdio-selenium-standalone-service": "~0.0.9",
"wdio-spec-reporter": "~0.1.2",
"webdriverio": "4.12.0"

**Comment by christian-bromann** [comment] 2018-04-03 11:37
duplicate of webdriverio/wdio-selenium-standalone-service#28

**Closed by christian-bromann** 2018-04-03 11:37 UTC
