### ISSUE TITLE
Click action fails to find element 

### ISSUE THREAD

**Issue by ElFredo311** [webdriverio/cucumber-boilerplate#451] opened 2021-01-22 06:30 UTC
# Issue description
> When trying to implement a 'When click on the element ' the application fails to find the element if xpath is used

# Steps to reproduce
> How can you reproduce the issue you are facing?
Running 

```
 Given I open the site "/business"
 Scenario: Existing element check - click
 When click on the element "#flash-message-alert-warning-announcement > div.alert__body > div.alert__link-wrap  > a"
 Then  I expect the url to contain "/home"
```

results on :
`Step "When click on the element "#flash-message-alert-warning-announcement > div.alert__body > div.alert__link-wrap  > a"" is not definedYou can ignore this error by setting cucumberOpts.ignoreUndefinedDefinitions as true.`\

However running:
```
 Given I open the site "/business"
 Scenario: Existing element check - click
 Then  I expect that element "#flash-message-alert-warning-announcement > div.alert__body > div.alert__link-wrap  > a" does exist
 Then  I expect the url to contain "/home"
```

does pass

# Expected behavior
> element selector should be able to find items by using the xpath

# Actual behavior
> elements are not found

# Issue occurred on browser/platform 
> IOS

**Comment by christian-bromann** [comment] 2021-03-24 10:40
Can you provide a reproducible example?

**Comment by gjw** [comment] 2021-05-12 18:53
Look in your steps to reproduce, looks like you forgot an " I "
 ("When click on the ")

**Comment by christian-bromann** [comment] 2021-09-20 08:46
Good catch @gjw , closing the issue. If you still see some unexpected behavior @ElFredo311 , let me know and I can re-open.

**Closed by christian-bromann** 2021-09-20 08:46 UTC
