### ISSUE TITLE
How can I add custom-header with the url I want to visit? For an example : x-original-host: for a particular locale or market?

### ISSUE THREAD

**Issue by raktim1988** [webdriverio/cucumber-boilerplate#486] opened 2022-03-23 13:31 UTC
# Issue description
> I cannot visit to a Url with specific/custom headers for each request, I tried with modheader , extension etc but it didn't work

# Expected behavior
> I expected either I can do it with added capabilities or just adding headers in the browser.url() function

# Issue occurred on browser/platform 
> this is generic and happens in all browsers/platform

**Comment by christian-bromann** [comment] 2022-03-23 13:54
duplicate of webdriverio/webdriverio#6361

**Closed by christian-bromann** 2022-03-23 13:54 UTC
